soc: qcom: Fix string format warning
Fix a string format warning:

 drivers/soc/qcom/service-notifier.c: In function 'add_service_notif':
 ./include/linux/kern_levels.h:5:18: error:
   format '%d' expects argument of type 'int', but argument 3 has type 'long int' [-Werror=format=]
 drivers/soc/qcom/service-notifier.c:515:3: note: in expansion of macro 'pr_err'

Fixes: 6ff955e258e1 ("soc: qcom: add snapshot of PIL, SSR, SYSMON and SERVICE LOCATOR")
Change-Id: Ic0dedbad3f624cc4125a06e233f772acd7654f76
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>