drivers: edac: Fix string format mismatch
Fix a few string format mismatches:

drivers/edac/kryo_arm64_edac.c:272:16: note: in expansion of macro 'KERN_CRIT'
error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'u64 {aka long long unsigned int}' [-Wformat=]

drivers/edac/kryo_arm64_edac.c:288:16: note: in expansion of macro 'KERN_CRIT'
error: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'u64 {aka long long unsigned int}' [-Werror=format=]

Fixes: 7d9fb5aea8d9 ("drivers: edac: Add Cache Error Reporting driver")
Change-Id: Ic0dedbad0c2d8895967b9fc2d34c446a53879186
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>