msm: msm_bus: Fix uninitalized variable compiler warning
 drivers/soc/qcom/msm_bus/msm_bus_of_rpmh.c:593:13: error:
   'size' is used uninitialized in this function [-Werror=uninitialized]

Change-Id: Ic0dedbad8851daa3fef306992ef3c6b69ea466e8
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>