soc: qcom: smp2p: Fix two warnings
 drivers/soc/qcom/smp2p.c: In function 'qcom_smp2p_do_ssr_ack':
 drivers/soc/qcom/smp2p.c:214:2: error:
   suggest parentheses around assignment used as truth value [-Werror=parentheses]

 drivers/soc/qcom/smp2p.c: In function 'qcom_smp2p_notify_in':
 drivers/soc/qcom/smp2p.c:176:23: error:
   format '%x' expects argument of type 'unsigned int', but argument 6 has type 'long unsigned int' [-Werror=format=]
 drivers/soc/qcom/smp2p.c:281:3: note: in expansion of macro 'SMP2P_INFO'

Fixes: 322d40176558 ("soc: qcom: smp2p: Add snapshot of smp2p driver")
Change-Id: Ic0dedbadbe4e61dd53e7bb22c54c2eb2ca94eb48
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>