soc: qcom: ipcc: Fix string format warning
 drivers/soc/qcom/qcom_ipcc.c: In function 'qcom_ipcc_domain_xlate':
 drivers/soc/qcom/qcom_ipcc.c:166:15: error:
  format '%x' expects argument of type 'unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]

Fixes: 65115211032b ("soc: qcom: ipcc: Add support for IPCC controller")
Change-Id: Ic0dedbadca8055804271b1ed38cf818cebe8d9a5
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>