backlight: qcom-spmi-wled: Fix a printk format compiler warning
 ./include/linux/kern_levels.h:5:18: error:
   format '%d' expects argument of type 'int', but argument 3 has type 'int64_t {aka long long int}

Change-Id: Ic0dedbad1a087d8ec75d97dabb839504aed27656
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>